# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnPrincipal.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QVBoxLayout,
    QWidget)

class Ui_vtnPrincipal(object):
    def setupUi(self, vtnPrincipal):
        if not vtnPrincipal.objectName():
            vtnPrincipal.setObjectName(u"vtnPrincipal")
        vtnPrincipal.resize(1121, 429)
        font = QFont()
        font.setPointSize(8)
        vtnPrincipal.setFont(font)
        self.centralwidget = QWidget(vtnPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(370, 300, 101, 41))
        self.btnGuardar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnlimpiar = QPushButton(self.centralwidget)
        self.btnlimpiar.setObjectName(u"btnlimpiar")
        self.btnlimpiar.setGeometry(QRect(700, 300, 101, 41))
        self.btnlimpiar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(270, 150, 301, 31))
        self.txtNombre.setMaxLength(100)
        self.cbsemestre = QComboBox(self.centralwidget)
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.addItem("")
        self.cbsemestre.setObjectName(u"cbsemestre")
        self.cbsemestre.setGeometry(QRect(800, 190, 181, 31))
        self.cbsemestre.setEditable(False)
        self.cbsemestre.setDuplicatesEnabled(False)
        self.cbsemestre.setFrame(True)
        self.txtApellido = QLineEdit(self.centralwidget)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setGeometry(QRect(270, 200, 301, 31))
        self.txtApellido.setMaxLength(100)
        self.txtcedula = QLineEdit(self.centralwidget)
        self.txtcedula.setObjectName(u"txtcedula")
        self.txtcedula.setGeometry(QRect(270, 100, 151, 31))
        self.txtcedula.setMaxLength(10)
        self.txtModaEstud = QLineEdit(self.centralwidget)
        self.txtModaEstud.setObjectName(u"txtModaEstud")
        self.txtModaEstud.setGeometry(QRect(800, 240, 181, 31))
        self.txtModaEstud.setInputMethodHints(Qt.ImhNone)
        self.txtModaEstud.setMaxLength(10)
        self.lbNombre = QLabel(self.centralwidget)
        self.lbNombre.setObjectName(u"lbNombre")
        self.lbNombre.setGeometry(QRect(180, 140, 91, 51))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.lbNombre.setFont(font1)
        self.lbApellido = QLabel(self.centralwidget)
        self.lbApellido.setObjectName(u"lbApellido")
        self.lbApellido.setGeometry(QRect(180, 190, 91, 51))
        self.lbApellido.setFont(font1)
        self.lbCedula = QLabel(self.centralwidget)
        self.lbCedula.setObjectName(u"lbCedula")
        self.lbCedula.setGeometry(QRect(190, 90, 81, 51))
        self.lbCedula.setFont(font1)
        self.lbFacultad = QLabel(self.centralwidget)
        self.lbFacultad.setObjectName(u"lbFacultad")
        self.lbFacultad.setGeometry(QRect(700, 90, 101, 51))
        self.lbFacultad.setFont(font1)
        self.lbModaEstud = QLabel(self.centralwidget)
        self.lbModaEstud.setObjectName(u"lbModaEstud")
        self.lbModaEstud.setGeometry(QRect(580, 230, 221, 51))
        self.lbModaEstud.setFont(font1)
        self.lbSemestre = QLabel(self.centralwidget)
        self.lbSemestre.setObjectName(u"lbSemestre")
        self.lbSemestre.setGeometry(QRect(690, 180, 101, 51))
        self.lbSemestre.setFont(font1)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 30, 121, 351))
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.btneliminar = QPushButton(self.groupBox)
        self.btneliminar.setObjectName(u"btneliminar")
        self.btneliminar.setMinimumSize(QSize(0, 23))
        self.btneliminar.setMaximumSize(QSize(161, 23))

        self.verticalLayout.addWidget(self.btneliminar)

        self.btnactualizar = QPushButton(self.groupBox)
        self.btnactualizar.setObjectName(u"btnactualizar")

        self.verticalLayout.addWidget(self.btnactualizar)

        self.btnbuscar = QPushButton(self.groupBox)
        self.btnbuscar.setObjectName(u"btnbuscar")

        self.verticalLayout.addWidget(self.btnbuscar)

        self.btninsertar = QPushButton(self.groupBox)
        self.btninsertar.setObjectName(u"btninsertar")

        self.verticalLayout.addWidget(self.btninsertar)

        self.cbfacultad = QComboBox(self.centralwidget)
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.addItem("")
        self.cbfacultad.setObjectName(u"cbfacultad")
        self.cbfacultad.setGeometry(QRect(800, 100, 181, 31))
        self.txtCarrera = QLineEdit(self.centralwidget)
        self.txtCarrera.setObjectName(u"txtCarrera")
        self.txtCarrera.setGeometry(QRect(800, 140, 301, 31))
        self.txtCarrera.setMaxLength(100)
        self.lbCarrera = QLabel(self.centralwidget)
        self.lbCarrera.setObjectName(u"lbCarrera")
        self.lbCarrera.setGeometry(QRect(710, 130, 91, 51))
        self.lbCarrera.setFont(font1)
        self.lbEdad = QLabel(self.centralwidget)
        self.lbEdad.setObjectName(u"lbEdad")
        self.lbEdad.setGeometry(QRect(210, 230, 61, 51))
        self.lbEdad.setFont(font1)
        self.spEdad = QSpinBox(self.centralwidget)
        self.spEdad.setObjectName(u"spEdad")
        self.spEdad.setGeometry(QRect(270, 240, 151, 31))
        vtnPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtnPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1121, 21))
        vtnPrincipal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtnPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        vtnPrincipal.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtcedula, self.txtNombre)
        QWidget.setTabOrder(self.txtNombre, self.txtApellido)
        QWidget.setTabOrder(self.txtApellido, self.cbfacultad)
        QWidget.setTabOrder(self.cbfacultad, self.txtModaEstud)
        QWidget.setTabOrder(self.txtModaEstud, self.cbsemestre)
        QWidget.setTabOrder(self.cbsemestre, self.btnGuardar)
        QWidget.setTabOrder(self.btnGuardar, self.btnlimpiar)
        QWidget.setTabOrder(self.btnlimpiar, self.btninsertar)
        QWidget.setTabOrder(self.btninsertar, self.btnbuscar)
        QWidget.setTabOrder(self.btnbuscar, self.btnactualizar)
        QWidget.setTabOrder(self.btnactualizar, self.btneliminar)

        self.retranslateUi(vtnPrincipal)

        QMetaObject.connectSlotsByName(vtnPrincipal)
    # setupUi

    def retranslateUi(self, vtnPrincipal):
        vtnPrincipal.setWindowTitle(QCoreApplication.translate("vtnPrincipal", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        vtnPrincipal.setToolTip(QCoreApplication.translate("vtnPrincipal", u"Ingrese solo n\u00fameros", None))
#endif // QT_CONFIG(tooltip)
        self.btnGuardar.setText(QCoreApplication.translate("vtnPrincipal", u"GUARDAR", None))
        self.btnlimpiar.setText(QCoreApplication.translate("vtnPrincipal", u"LIMPIAR", None))
        self.txtNombre.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"NOMBRE ESTUDIANTE", None))
        self.cbsemestre.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.cbsemestre.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"1er", None))
        self.cbsemestre.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"2do", None))
        self.cbsemestre.setItemText(3, QCoreApplication.translate("vtnPrincipal", u"3er", None))
        self.cbsemestre.setItemText(4, QCoreApplication.translate("vtnPrincipal", u"4to", None))
        self.cbsemestre.setItemText(5, QCoreApplication.translate("vtnPrincipal", u"5to", None))
        self.cbsemestre.setItemText(6, QCoreApplication.translate("vtnPrincipal", u"6to", None))
        self.cbsemestre.setItemText(7, QCoreApplication.translate("vtnPrincipal", u"7mo", None))
        self.cbsemestre.setItemText(8, QCoreApplication.translate("vtnPrincipal", u"8vo", None))
        self.cbsemestre.setItemText(9, QCoreApplication.translate("vtnPrincipal", u"9no", None))
        self.cbsemestre.setItemText(10, QCoreApplication.translate("vtnPrincipal", u"10mo", None))

        self.cbsemestre.setCurrentText(QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.txtApellido.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"APELLIDO ESTUDIANTE", None))
#if QT_CONFIG(tooltip)
        self.txtcedula.setToolTip(QCoreApplication.translate("vtnPrincipal", u"Ingrese solo n\u00fameros", None))
#endif // QT_CONFIG(tooltip)
        self.txtcedula.setInputMask("")
        self.txtcedula.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"CEDULA ESTUDIANTE", None))
        self.txtModaEstud.setInputMask("")
        self.txtModaEstud.setText("")
        self.txtModaEstud.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"Presencial, virtual e hibrida", None))
        self.lbNombre.setText(QCoreApplication.translate("vtnPrincipal", u"Nombre:", None))
        self.lbApellido.setText(QCoreApplication.translate("vtnPrincipal", u"Apellido:", None))
        self.lbCedula.setText(QCoreApplication.translate("vtnPrincipal", u"Cedula:", None))
        self.lbFacultad.setText(QCoreApplication.translate("vtnPrincipal", u"Facultad:", None))
        self.lbModaEstud.setText(QCoreApplication.translate("vtnPrincipal", u"Modalidad de estudio:", None))
        self.lbSemestre.setText(QCoreApplication.translate("vtnPrincipal", u"Semestre:", None))
        self.groupBox.setTitle("")
        self.btneliminar.setText(QCoreApplication.translate("vtnPrincipal", u"Eliminar", None))
        self.btnactualizar.setText(QCoreApplication.translate("vtnPrincipal", u"Actualizar", None))
        self.btnbuscar.setText(QCoreApplication.translate("vtnPrincipal", u"Buscar", None))
        self.btninsertar.setText(QCoreApplication.translate("vtnPrincipal", u"Insertar", None))
        self.cbfacultad.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.cbfacultad.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Facultad de Arquitectura y Urbanismo", None))
        self.cbfacultad.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Administrativas", None))
        self.cbfacultad.setItemText(3, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Agrarias", None))
        self.cbfacultad.setItemText(4, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Econ\u00f3micas", None))
        self.cbfacultad.setItemText(5, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Matem\u00e1ticas y F\u00edsicas", None))
        self.cbfacultad.setItemText(6, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias M\u00e9dicas", None))
        self.cbfacultad.setItemText(7, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Psicol\u00f3gicas", None))
        self.cbfacultad.setItemText(8, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Qu\u00edmicas", None))
        self.cbfacultad.setItemText(9, QCoreApplication.translate("vtnPrincipal", u"Facultad de Comunicaci\u00f3n Social", None))
        self.cbfacultad.setItemText(10, QCoreApplication.translate("vtnPrincipal", u"Facultad de Educaci\u00f3n F\u00edsica,\n"
"Deportes y Recreaci\u00f3n", None))
        self.cbfacultad.setItemText(11, QCoreApplication.translate("vtnPrincipal", u"Facultad de Filosof\u00eda,\n"
"Letras y Ciencias de la\n"
"Educaci\u00f3n", None))
        self.cbfacultad.setItemText(12, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ingenier\u00eda\n"
"Industrial", None))
        self.cbfacultad.setItemText(13, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ingenier\u00eda\n"
"Qu\u00edmica", None))
        self.cbfacultad.setItemText(14, QCoreApplication.translate("vtnPrincipal", u"Facultad deJurisprudenciaycienicasSocialesyPol\u00edticas", None))
        self.cbfacultad.setItemText(15, QCoreApplication.translate("vtnPrincipal", u"Facultad de Medicina\n"
"Veterinaria y\n"
"Zootecnia", None))
        self.cbfacultad.setItemText(16, QCoreApplication.translate("vtnPrincipal", u"Facultad Piloto de\n"
"Odontolog\u00eda", None))
        self.cbfacultad.setItemText(17, QCoreApplication.translate("vtnPrincipal", u"Facultad de Ciencias Naturales\n"
"\n"
"", None))

        self.txtCarrera.setText("")
        self.txtCarrera.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"INGRESE SU CARRERA", None))
        self.lbCarrera.setText(QCoreApplication.translate("vtnPrincipal", u"Carrera:", None))
        self.lbEdad.setText(QCoreApplication.translate("vtnPrincipal", u"Edad:", None))
    # retranslateUi

